// Deterministic sender rules, evaluated in order; first match wins.
// Edit this file to teach the classifier about a sender without touching the model.
//
// Each rule: { match, subject?, label? , inbox? , id? }
//   match:   string  -> matches if the sender address ends with it (domain) or equals it (full address), case-insensitive
//            RegExp  -> tested against the full "From" header
//   subject: optional RegExp the subject must match
//   label:   one of reply_needed | action_required | reference | client_fyi | invoices | notification | spam
//   inbox:   true -> do not decide the label, but guarantee the result stays in the inbox
//            (the model still picks between the four inbox labels)
//   hold:    minutes to keep a notification in the inbox before filing (default 5)

export const SENDER_RULES = [
  // --- Known clients, partners, family: always inbox. Model picks which inbox label. ---
  { match: 'bayleys.co.nz', inbox: true },
  { match: 'nzsir.com', inbox: true },
  { match: 'northnzsir.com', inbox: true },
  { match: 'bnbgroup.co.nz', inbox: true },
  { match: 'payper.co', inbox: true },
  { match: 'tenpasttomorrow.com', inbox: true },
  { match: 'commscouncil.nz', inbox: true },
  { match: 'nautica.co.nz', inbox: true },
  { match: 'jle.co.nz', inbox: true },
  { match: 'smoke.co.nz', inbox: true },
  { match: 'patersonluxury.co.nz', inbox: true },
  { match: 'nectar.photography', inbox: true },
  { match: 'guardiansmith.co.nz', inbox: true },
  { match: 'ajg.co.nz', inbox: true },
  { match: 'claims@tower.co.nz', inbox: true },
  { match: 'hannoverfairs.com.au', inbox: true },
  { match: 'shoretreeservices.co.nz', inbox: true },
  { match: 'h88photoediting@gmail.com', inbox: true },
  { match: 'hasleralisha@gmail.com', inbox: true },
  { match: 'markushaslernz@outlook.com', inbox: true },
  { match: 'lukehasler7@gmail.com', inbox: true },
  // Accountant: humans are inbox, their invoices/DD are invoices, their mailers are spam
  { match: 'send.sba.co.nz', label: 'spam' },
  { match: 'burnside@sba.co.nz', label: 'notification' },
  { match: 'sba.co.nz', inbox: true },

  // --- Platforms relaying a person ---
  { match: 'pixiesetmail.com', subject: /form submission/i, label: 'reply_needed' },
  { match: 'pixiesetmail.com', subject: /store order/i, label: 'action_required' },
  { match: 'pixiesetmail.com', label: 'notification' },
  { match: 'builderscrack.co.nz', subject: /^message from/i, label: 'action_required' },
  { match: 'builderscrack.co.nz', label: 'notification' },
  { match: 'express@airbnb.com', label: 'action_required' },
  { match: 'automated@airbnb.com', subject: /confirmation code/i, label: 'notification', hold: 30 },
  { match: 'automated@airbnb.com', label: 'invoices' },

  // --- Money: paid / auto-collected -> invoices, must act -> action_required ---
  { match: 'post.xero.com', subject: /payment has been made/i, label: 'invoices' },
  { match: 'post.xero.com', subject: /sba burnside/i, label: 'invoices' },
  { match: 'gocardless.com', label: 'invoices' },
  { match: 'payments-noreply@google.com', label: 'invoices' },
  { match: /invoice\+statements/i, label: 'invoices' },
  { match: 'stripe.com', label: 'invoices' },
  { match: 'receipts@openrouter.ai', label: 'invoices' },
  { match: 'imagen-ai.com', label: 'invoices' },
  { match: 'comms.2degrees.nz', label: 'invoices' },
  { match: 'water.co.nz', label: 'invoices' },
  { match: 'bunny.net', subject: /invoice|recharge|payment/i, label: 'invoices' },
  { match: 'insurance@tower.co.nz', subject: /overdue|failed|due/i, label: 'action_required' },
  { match: 'insurance@tower.co.nz', label: 'invoices' },
  { match: 'pbtech.co.nz', subject: /invoice paid|receipt/i, label: 'invoices' },
  { match: 'email.apple.com', label: 'invoices' },
  { match: 't1.rechargemail.com', label: 'invoices' },
  { match: 't.shopifyemail.com', label: 'invoices' },
  { match: 'vimeo.com', subject: /receipt|purchase/i, label: 'invoices' },
  { match: 'vimeo.com', label: 'notification' },
  { match: 'intl.paypal.com', subject: /stay logged in|trusted device|new device/i, label: 'notification' },
  { match: 'intl.paypal.com', label: 'invoices' },
  { match: 'blackbox.global', label: 'invoices' },
  { match: 'hi@cursor.com', subject: /couldn.t process|payment failed|past due/i, label: 'action_required' },
  { match: 'studioninja.app', subject: /payment.*failed|failed.*payment/i, label: 'action_required' },
  { match: 'rates.aucklandcouncil.govt.nz', label: 'action_required' },
  { match: 'aucklandcouncil.govt.nz', subject: /rates/i, label: 'action_required' },
  { match: 'companies.govt.nz', label: 'action_required' },
  { match: 'ext.acc.co.nz', label: 'notification' },
  { match: 'stock.adobe.com', label: 'notification' },
  { match: 'Stock@adobe.com', label: 'notification' },

  // --- Status only ---
  { match: 'notice.aliexpress.com', subject: /how did it go/i, label: 'spam' },
  { match: 'notice.aliexpress.com', label: 'notification' },
  { match: 'nzpost.co.nz', label: 'notification' },
  { match: 'garmin.com', label: 'notification' },
  { match: 'accounts.google.com', label: 'notification' },
  { match: 'mail.anthropic.com', label: 'notification', hold: 30 },
  { match: 'site.trademe.co.nz', label: 'notification', hold: 30 },
  { match: 'id.clubplus.co.nz', label: 'notification', hold: 30 },
  { match: 'dropbox.com', label: 'notification' },
  { match: 'notify.railway.app', label: 'notification' },
  { match: 'synologynotification.com', label: 'notification' },
  { match: 'sciener.com', label: 'notification' },
  { match: 'getflywheel.com', label: 'notification' },
  { match: 'updates.fresha.com', label: 'notification' },
  { match: 'github.com', label: 'notification' },
  { match: 'revolut.com', label: 'notification' },
  { match: 'ironline.ird.govt.nz', label: 'notification' },
  { match: 'pizzahut.co.nz', label: 'notification' },
  { match: 'mightyape.co.nz', subject: /order|shipped|delivery|delivered/i, label: 'notification' },

  // --- Marketing / newsletters / prospecting -> Email Prison ---
  { match: 'daily.therundown.ai', label: 'spam' },
  { match: 'substack.com', label: 'spam' },
  { match: 'email.openai.com', label: 'spam' },
  { match: /@[a-z0-9.-]*aliexpress\.com/i, label: 'spam' },
  { match: 'temuemail.com', label: 'spam' },
  { match: 'temuofficial.com', label: 'spam' },
  { match: 'onlinemeats.co.nz', label: 'spam' },
  { match: 'hello.klarna.com', label: 'spam' },
  { match: 'hallertau.co.nz', label: 'spam' },
  { match: 'cullenkellycolor.com', label: 'spam' },
  { match: 'barfoot.co.nz', label: 'spam' },
  { match: 'raywhite.com', label: 'spam' },
  { match: 'harcourts.co.nz', label: 'spam' },
  { match: 'communications.anz.co.nz', label: 'spam' },
  { match: 'seek.co.nz', label: 'spam' },
  { match: 'cosmos.so', label: 'spam' },
  { match: 'tailscale.com', label: 'spam' },
  { match: 'welcome@openrouter.ai', label: 'spam' },
  { match: 'news.railway.app', label: 'spam' },
  { match: 'email.claude.com', label: 'spam' },
  { match: 'welcome@supabase.com', label: 'spam' },
  { match: 'mitre10trade.co.nz', label: 'spam' },
  { match: 'golf.co.nz', label: 'spam' },
  { match: 'vip.dominos.co.nz', label: 'spam' },
  { match: 'e.mightyape.co.nz', label: 'spam' },
  { match: 'grabone.co.nz', label: 'spam' },
  { match: 'email.magnolia.com', label: 'spam' },
  { match: 'marketing.pinterest.com', label: 'spam' },
  { match: 'mail.skylum.com', label: 'spam' },
  { match: 'snowplanet.co.nz', label: 'spam' },
  { match: 'booster.co.nz', label: 'spam' },
  { match: 'vetpost.co.nz', subject: /order/i, label: 'invoices' },
  { match: 'vetpost.co.nz', label: 'spam' },
];
